language: php
php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

branches:
  only:
  - /.*/

before_script:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - ./composer.phar install --prefer-dist --no-interaction
  - ./composer.phar require --dev squizlabs/php_codesniffer:dev-master
  - ./composer.phar require --dev satooshi/php-coveralls:dev-master
  - mkdir -p ./build/logs

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
- php bin/coveralls -v

notifications:
  email: false
